language: python
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  cleanup: false
  provider: heroku
  api_key:
    secure: WTVGtw+JUbwoFUW2Req3VhS/I6stKdSRhzKTbnFNESWt+43aoZLK2ZVm6ajKr7O/pB7nc9L8n/vGLrtB3Uqth9ubdK1FJ9tIytdMV0S+WiPy4BDpXTjI29lSCcK2GCVKeESwjuJ4LJxi2IItA4tJ88mF/64npVKs4ZUCa2SJQBdXqYAjL1J4WU7TnGql0QpzoXBXa+uoA4bA/WbyNAdbHjCPBTNKm4PQJLfRrIgi33idxg3qYlK3RVLKnIzkiby30xPBAFi5Caz2Xu1HHVWyMiPxDBVcraYWUX4Wh298mwhDtBjcXEEIinxDOo07wuW7LTnzqdrYhbuRqEyJoJutY4ZGFGDEDjajR/99U4hKzZcefDDLUV/apQ/rtqKOee8fhuvI1eDsrcBp0xntcVggrr81gqLpcVHYLXPMcKgCep1YRHhnyAW3M693glZ5BBeIEl1SfXtk9p/535BA9V0ascxb6iy6+JPPf7r0zasudbs8OJLa7CIqOTQZZfg0pvu1yrealFyojXzHkHXJ4gyDOBoDhHnwMxJPdkhkiKHePYkorSmafkEYu5bgFHMJg7nZ3DFn/x9m85mAFtCYFhhrN3uv3SDz70yFICdt+PWPyWi6ZjKZ8niLnil2W6dTjbEuufIknGK6r7/TKu9AWVTgZL2KuOGnNdZFjvIXfcN/EEk=
  app: uva3240quicktutor
  on:
    repo: uva-cs3240-s20/project-102-tuber
  run: "python3 manage.py migrate --run-syncdb"
