# Generated by Django 3.0.3 on 2020-02-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='pub_date',
        ),
    ]
