# Generated by Django 3.0.3 on 2020-03-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0003_helprequest_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='topic_text',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=models.CharField(choices=[('clem', 'Clemons Library'), ('aldy', 'Alderman Library'), ('clark', 'Clark Library'), ('music', 'Music Library'), ('rice', 'Rice Hall')], default='green', max_length=6),
        ),
    ]
