# Generated by Django 3.0.3 on 2020-04-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0004_auto_20200303_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='times',
            field=models.IntegerField(choices=[(5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=5),
        ),
    ]
