# Generated by Django 3.0.3 on 2020-04-06 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0007_auto_20200406_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 16, 44, 56, 940967)),
        ),
    ]
