# Generated by Django 3.0.3 on 2020-04-06 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0008_helprequest_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
