# Generated by Django 3.0.3 on 2020-04-06 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0009_auto_20200406_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, max_length=100),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='location',
            field=models.CharField(choices=[('Clemons Library', 'Clemons Library'), ('Alderman Library', 'Alderman Library'), ('Clark Library', 'Clark Library'), ('Music Library', 'Music Library'), ('Rice Hall', 'Rice Hall')], default='green', max_length=60),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='time',
            field=models.IntegerField(choices=[(5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=5, max_length=100),
        ),
    ]
