# Generated by Django 3.0.3 on 2020-04-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0010_auto_20200406_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='time',
            field=models.IntegerField(choices=[(5, '5 Minutes'), (10, '10 Minutes'), (15, '15 Minutes'), (30, '30 Minutes'), (60, '1 Hour')], default=5),
        ),
    ]
