# Generated by Django 3.0.3 on 2020-04-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_help', '0012_helprequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='phone',
            field=models.CharField(default='XXXXXXXXXX', max_length=60),
        ),
    ]
