# Generated by Django 3.0.3 on 2020-02-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='defaultname', max_length=100),
            preserve_default=False,
        ),
    ]
