# Generated by Django 3.0.3 on 2020-04-13 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200331_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='register.UserProfile')),
            ],
        ),
    ]
