# Generated by Django 3.0 on 2020-03-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200329_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status_string',
            field=models.CharField(default='Not Available', max_length=30),
        ),
    ]
