# Generated by Django 3.0 on 2020-03-17 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorStatus', '0002_auto_20200227_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorStatus',
        ),
    ]
